const $ = id => document.getElementById(id);
const logEl = $('log');
let launcherState = null;
let selectedVersion = '1.21.11';
let selectedHat = 'vortex-cap';
let selectedEmblem = 'vortex-crest';
let templateModResults = [];
let installedCollapsed = false;
let resourcePackResults = [];
let resourcePackSearchState = { query: '', version: '1.21.11', page: 0, total: 0, hasNext: false };

const hatNames = { none: 'Kein Hut', 'vortex-cap': 'Vortex Cap', 'neon-halo': 'Neon Halo', 'void-crown': 'Void Crown', 'cyber-headphones': 'Cyber Headphones', 'slime-antenna': 'Slime Antenna' };
const emblemNames = { none: 'Kein Cape', 'vortex-crest': 'Vortex Cape', 'nebula-mark': 'Nebula Cape', 'void-rune': 'Void Cape' };
const escapeHtml = value => String(value).replace(/[<>&]/g, char => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[char]));
const escapeAttr = value => escapeHtml(value).replace(/['"]/g, char => char === '"' ? '&quot;' : '&#39;');

function addLog(message, tone = '') { const item = document.createElement('div'); item.className = `log-line ${tone}`; item.innerHTML = `<span class="log-time">${new Date().toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}</span><span>${escapeHtml(message)}</span>`; logEl.appendChild(item); logEl.scrollTop = logEl.scrollHeight; }
function setStatus(message) { $('statusText').textContent = message; }
function setAccount(account) { const element = $('account'); if (!account) { element.innerHTML = '<div class="avatar">?</div><div><strong>Nicht angemeldet</strong><span>Minecraft Microsoft-Konto</span></div><button class="button secondary small" id="loginBtn">Anmelden</button>'; $('loginBtn').onclick = login; return; } element.innerHTML = `<div class="avatar signed">${escapeHtml(account.username.slice(0, 2).toUpperCase())}</div><div><strong>${escapeHtml(account.username)}</strong><span>Minecraft Microsoft-Konto</span></div><button class="button secondary small" id="loginBtn">Abmelden</button>`; $('loginBtn').onclick = logout; }
function currentSummary() { return launcherState?.versions?.find(instance => instance.version === selectedVersion); }
function cosmeticsSummary() { return launcherState?.versions?.find(instance => instance.version === launcherState?.cosmeticsVersion); }
function updatePlaySummary() { const summary = currentSummary(); $('selectedVersionLabel').textContent = selectedVersion; $('coreStatus').textContent = summary?.ready ? 'Aktiv' : 'Bereitstellen'; $('modCount').textContent = summary ? `${summary.totalModCount} Mods` : '— Mods'; }
function modScopeLabel() { const scope = $('modScope'); if (scope) scope.textContent = `for ${selectedVersion}`; }

function renderVersions() { const select = $('versionSelect'); const options = launcherState.versions.map(item => `<option value="${item.version}">${item.version} · Fabric + Vortex Client${item.cosmeticsSupported ? ' · Cosmetics' : ''}</option>`).join(''); select.innerHTML = options; select.value = selectedVersion; select.onchange = async event => { selectedVersion = event.target.value; await window.vortex.selectVersion(selectedVersion); updatePlaySummary(); renderInstanceCards(); modScopeLabel(); await refreshInstalled(); await renderOverview(); }; }
function renderInstanceCards() { $('instancesGrid').innerHTML = launcherState.versions.map(instance => { const active = instance.version === selectedVersion ? ' selected' : ''; const state = instance.ready ? 'Bereit' : 'Nicht installiert'; const cosmeticLine = instance.cosmeticsSupported ? `<div class="instance-stat accent"><span>COSMETICS</span><strong>${instance.cosmeticProfile?.generatedSkin ? 'Aktiv' : 'Bereit'}</strong></div>` : '<div class="instance-stat"><span>COSMETICS</span><strong>1.21.11</strong></div>'; return `<article class="instance-card${active}"><div class="instance-title"><div><h3>${instance.version}</h3><p>FABRIC + VORTEX CLIENT</p></div><span class="instance-state">${state}</span></div><div class="instance-stats"><div class="instance-stat"><span>PFLICHTMODS</span><strong>${instance.coreModCount}</strong></div><div class="instance-stat"><span>GESAMT</span><strong>${instance.totalModCount} Mods</strong></div>${cosmeticLine}</div><div class="instance-actions"><button class="button secondary" data-select="${instance.version}">Auswählen</button><button class="button secondary" data-prepare="${instance.version}">Prüfen</button><button class="button ghost" data-mods="${instance.version}">Mods</button></div></article>`; }).join(''); document.querySelectorAll('[data-select]').forEach(button => button.onclick = async () => { selectedVersion = button.dataset.select; await window.vortex.selectVersion(selectedVersion); $('versionSelect').value = selectedVersion; updatePlaySummary(); renderInstanceCards(); modScopeLabel(); await refreshInstalled(); await renderOverview(); showPage('play'); }); document.querySelectorAll('[data-prepare]').forEach(button => button.onclick = () => prepare(button.dataset.prepare)); document.querySelectorAll('[data-mods]').forEach(button => button.onclick = () => window.vortex.openModsFolder(button.dataset.mods)); }
function updateCosmetics() { $('cosmeticName').textContent = hatNames[selectedHat]; $('emblemName').textContent = emblemNames[selectedEmblem]; $('cosmeticPreview').className = `cosmetic-shape ${selectedHat === 'void-crown' ? 'purple' : selectedHat === 'neon-halo' ? 'cyan' : selectedHat === 'slime-antenna' ? 'green' : ''}`; document.querySelectorAll('.hat-card').forEach(card => card.classList.toggle('selected', card.dataset.hat === selectedHat)); document.querySelectorAll('.emblem-card').forEach(card => card.classList.toggle('selected', card.dataset.emblem === selectedEmblem)); const summary = cosmeticsSummary(); const profile = summary?.cosmeticProfile; const status = $('cosmeticsStatus'); if (!summary?.cosmeticsSupported) status.textContent = 'Die Cosmetics-Ausgabe für 1.21.11 wird vorbereitet.'; else if (profile?.generatedSkin) status.innerHTML = `<strong>Bereit:</strong> ${escapeHtml(profile.generatedSkin)} · ${escapeHtml(hatNames[profile.hat] || profile.hat)} + ${escapeHtml(emblemNames[profile.emblem] || profile.emblem)}`; else status.textContent = 'Noch keine Skin-Variante erstellt. Wähle deinen Look und importiere einen 64×64-Skin.'; }

function updateUpdateView(update = launcherState?.update || {}) { const labels = { idle: 'Bereit', checking: 'Suche läuft …', available: 'Update verfügbar', downloading: 'Download läuft …', downloaded: 'Bereit zur Installation', 'up-to-date': 'Aktuell', dev: 'Entwicklermodus', error: 'Fehler' }; const messages = { idle: 'Noch nicht auf Updates geprüft.', checking: 'Die GitHub-Releases werden geprüft …', available: `Version ${update.availableVersion} ist verfügbar.`, downloading: `Update wird heruntergeladen: ${update.progress || 0} %`, downloaded: `Version ${update.availableVersion} wurde heruntergeladen und kann installiert werden.`, 'up-to-date': 'Du verwendest bereits die neueste Version.', dev: update.error || 'Updates sind im Entwicklungsmodus deaktiviert.', error: update.error || 'Die Update-Prüfung ist fehlgeschlagen.' }; const progress = Math.max(0, Math.min(100, update.progress || 0)); $('currentVersion').textContent = update.currentVersion || '0.4.8'; $('availableVersion').textContent = update.availableVersion || (update.status === 'up-to-date' ? 'Aktuell' : '—'); $('updateBadge').textContent = labels[update.status] || 'Bereit'; $('updateStatus').textContent = messages[update.status] || messages.idle; $('updateProgressBar').style.width = `${progress}%`; $('updateProgressValue').textContent = `${progress} %`; $('downloadUpdateBtn').disabled = update.status !== 'available'; $('installUpdateBtn').disabled = update.status !== 'downloaded'; }
async function checkUpdate() { $('checkUpdateBtn').disabled = true; updateUpdateView({ ...(launcherState?.update || {}), status: 'checking' }); const result = await window.vortex.checkForUpdates(); launcherState.update = result; updateUpdateView(result); $('checkUpdateBtn').disabled = false; }
async function downloadUpdate() { $('downloadUpdateBtn').disabled = true; const result = await window.vortex.downloadUpdate(); launcherState.update = result; updateUpdateView(result); }
async function installUpdate() { const result = await window.vortex.installUpdate(); if (!result.ok) addLog(result.error, 'error'); }

// Mod installer — exactly the layout and interaction model from the supplied source ZIP.
function templateIcon(hit) { const letter = escapeHtml((hit.title || '?').slice(0, 1).toUpperCase()); const iconUrl = /^https:\/\/cdn\.modrinth\.com\//i.test(hit.iconUrl || '') ? hit.iconUrl : null; return iconUrl ? `<img class="mod-icon" src="${escapeAttr(iconUrl)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'mod-icon fallback',textContent:'${letter}'}))" />` : `<span class="mod-icon fallback">${letter}</span>`; }
function renderModResults(hits) { const box = $('modResults'); if (!hits.length) { box.innerHTML = '<p class="mod-empty">Nothing found. Try another term.</p>'; return; } box.innerHTML = hits.map((hit, index) => { const button = hit.installed ? '<button class="button small" disabled>Already installed</button>' : `<button class="button small" data-install="${index}">Installieren</button>`; return `<article class="mod-card${hit.installed ? ' has-mod' : ''}">${templateIcon(hit)}<div class="mod-body"><strong>${escapeHtml(hit.title)}</strong><p>${escapeHtml(hit.description || '')}</p><small>${Number(hit.downloads || 0).toLocaleString('en-GB')} downloads${hit.author ? ' · ' + escapeHtml(hit.author) : ''}</small></div>${button}</article>`; }).join(''); box.querySelectorAll('[data-install]').forEach(button => button.onclick = () => installTemplateMod(Number(button.dataset.install), button)); }
async function searchTemplateMods() { const query = $('modQuery').value.trim(); if (!query) { setStatus('Enter a search term.'); return; } const button = $('modSearchBtn'); button.disabled = true; $('modResults').innerHTML = '<p class="mod-empty">Searching …</p>'; const result = await window.vortex.searchMods(query, selectedVersion, 0); button.disabled = false; if (!result.ok) { $('modResults').innerHTML = `<p class="mod-empty">${escapeHtml(result.error || 'Search failed.')}</p>`; return; } templateModResults = result.results || []; renderModResults(templateModResults); }
async function installTemplateMod(index, button) { const hit = templateModResults[index]; if (!hit) return; button.disabled = true; const label = button.textContent; button.textContent = 'Downloading …'; addLog(`Installing ${hit.title} for ${selectedVersion} …`); const result = await window.vortex.installModProject(hit.projectId, selectedVersion); if (result.ok) { hit.installed = true; button.textContent = 'Installed'; addLog(`${hit.title}: ${(result.installed || []).length + (result.present || []).length} file(s) in the mods folder.`, 'success'); await refreshInstalled(); await renderOverview(); await refresh(); } else { button.textContent = label; button.disabled = false; addLog(result.error || 'Installation failed.', 'error'); } }
async function refreshInstalled() { const box = $('installedMods'); if (!box || !launcherState) return; const list = await window.vortex.listMods(selectedVersion); if (!list.length) { box.innerHTML = '<p class="mod-empty">No mods in this instance yet.</p>'; return; } box.hidden = installedCollapsed; box.innerHTML = list.map(mod => `<div class="installed-row"><span>${escapeHtml(mod.name)}</span><button class="text-button" data-installed-remove="${escapeAttr(mod.file || mod.name)}">Remove</button></div>`).join(''); box.querySelectorAll('[data-installed-remove]').forEach(button => button.onclick = async () => { const result = await window.vortex.removeMod(selectedVersion, button.dataset.installedRemove); if (!result.ok) addLog(result.error || 'Could not remove this Vortex file.', 'error'); else addLog(`${button.dataset.installedRemove} removed.`, 'success'); await refreshInstalled(); await renderOverview(); }); }

// Installed mods — exact card, totals, switch and remove model from the supplied source ZIP.
function formatSize(bytes) { if (!bytes) return ''; const mb = bytes / 1048576; return mb >= 1 ? `${mb.toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`; }
async function renderOverview() { const list = $('overviewList'); const totals = $('overviewTotals'); if (!list || !launcherState) return; list.innerHTML = '<p class="mod-empty">Loading …</p>'; const mods = await window.vortex.listMods(selectedVersion); const active = mods.filter(mod => mod.enabled).length; const own = mods.filter(mod => !mod.required).length; $('ovInstance').textContent = `Minecraft ${selectedVersion}`; totals.innerHTML = `<div class="total-card"><span>${active}</span><small>Active</small></div><div class="total-card"><span>${mods.length - active}</span><small>Disabled</small></div><div class="total-card"><span>${own}</span><small>Added by you</small></div><div class="total-card"><span>${escapeHtml(selectedVersion)}</span><small>Version</small></div>`; if (!mods.length) { list.innerHTML = '<p class="mod-empty">Nothing installed yet. Pick a version above.</p>'; return; } list.innerHTML = mods.map(mod => { const title = mod.name.replace(/\.jar$/, ''); const letter = escapeHtml(title.slice(0, 1).toUpperCase()); const source = mod.protected ? '../assets/branding/vortex-logo.png' : null; const icon = source ? `<img class="mod-icon own" src="${source}" alt="" />` : `<span class="mod-icon fallback">${letter}</span>`; const origin = mod.protected ? 'Vortex core' : mod.required ? 'Vortex required' : 'Added by you'; const actions = mod.required ? '<span class="ov-lock" title="Belongs to Vortex Client — cannot be disabled or removed">Fixed</span>' : `<button class="mod-switch${mod.enabled ? ' on' : ''}" data-mod="${escapeAttr(mod.file || mod.name)}" aria-label="${mod.enabled ? 'Turn off' : 'Turn on'}"><span></span></button><button class="ov-remove" data-overview-remove="${escapeAttr(mod.file || mod.name)}" title="Remove from this instance" aria-label="Remove">✕</button>`; return `<article class="mod-card ov-card${mod.enabled ? '' : ' off'}">${icon}<div class="mod-body"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(mod.name)}</p><small>${origin}</small></div><div class="ov-actions">${actions}</div></article>`; }).join(''); list.querySelectorAll('[data-overview-remove]').forEach(button => button.onclick = async () => { const name = button.dataset.overviewRemove; if (!confirm(`Remove ${name} from this instance?`)) return; button.disabled = true; const result = await window.vortex.removeMod(selectedVersion, name); addLog(result.ok ? `${name} removed.` : (result.error || `Could not remove ${name}.`), result.ok ? 'success' : 'error'); await renderOverview(); await refreshInstalled(); }); list.querySelectorAll('[data-mod]').forEach(button => button.onclick = async () => { button.disabled = true; const result = await window.vortex.toggleMod(selectedVersion, button.dataset.mod); if (!result.ok) addLog(result.error || 'Could not toggle.', 'error'); else addLog(`${button.dataset.mod.replace(/\.disabled$/, '')} ${result.enabled ? 'enabled' : 'disabled'}.`, 'success'); await renderOverview(); await refreshInstalled(); }); }

function projectIcon(pack) { const fallback = escapeHtml(pack.title.slice(0, 1).toUpperCase()); const iconUrl = /^https:\/\/cdn\.modrinth\.com\//i.test(pack.iconUrl || '') ? pack.iconUrl : null; return iconUrl ? `<img src="${escapeAttr(iconUrl)}" alt="" loading="lazy" referrerpolicy="no-referrer"><span class="online-mod-fallback">${fallback}</span>` : `<span class="online-mod-fallback">${fallback}</span>`; }
function bindProjectIcons(container) { container.querySelectorAll('.online-mod-icon img').forEach(image => { image.onerror = () => image.remove(); }); }
function updatePagination(prefix, state) { const page = state.page + 1; $(`${prefix}PageLabel`).textContent = `Seite ${page} · ${state.total.toLocaleString('de-DE')} Treffer`; $(`${prefix}PrevBtn`).disabled = state.page <= 0; $(`${prefix}NextBtn`).disabled = !state.hasNext; }
function renderResourcePacks() { const container = $('resourcePackResults'); if (!resourcePackResults.length) { container.innerHTML = '<div class="empty-library">Keine kompatiblen Resource Packs gefunden. Probiere einen anderen Namen.</div>'; updatePagination('packs', resourcePackSearchState); return; } container.innerHTML = resourcePackResults.map((pack, index) => `<article class="online-mod-card resource-pack-card"><div class="online-mod-icon">${projectIcon(pack)}</div><div class="online-mod-main"><div class="online-mod-title"><h3>${escapeHtml(pack.title)}</h3><span class="mod-badge pack-badge">${escapeHtml(pack.versionType || 'release')}</span></div><p>${escapeHtml(pack.description)}</p><small>${escapeHtml(pack.versionNumber)} · ${escapeHtml(pack.gameVersion)} · ${escapeHtml((pack.categories || []).slice(0, 3).join(' · '))} · ${Number(pack.downloads || 0).toLocaleString('de-DE')} Downloads</small></div><button class="button secondary mod-download-button" data-pack-index="${index}">Pack laden</button></article>`).join(''); bindProjectIcons(container); updatePagination('packs', resourcePackSearchState); container.querySelectorAll('[data-pack-index]').forEach(button => button.onclick = () => downloadResourcePack(Number(button.dataset.packIndex), button)); }
async function searchResourcePacks(page = 0) { const query = $('resourcePackSearchInput').value.trim(); const version = $('resourcePackVersion').value || selectedVersion; const button = $('searchResourcePacksBtn'); if (query.length < 2) { $('resourcePackSearchStatus').textContent = 'Bitte gib mindestens zwei Zeichen ein.'; return; } button.disabled = true; $('resourcePackSearchStatus').textContent = `Suche nach „${query}“ · Seite ${page + 1} …`; $('resourcePackResults').innerHTML = '<div class="empty-library">Weitere Resource Packs werden geladen …</div>'; const result = await window.vortex.searchResourcePacks(query, version, page); button.disabled = false; if (!result.ok) { resourcePackResults = []; $('resourcePackSearchStatus').textContent = result.error || 'Die Resource-Pack-Suche ist fehlgeschlagen.'; renderResourcePacks(); return; } resourcePackSearchState = { query, version, page: result.page || page, total: result.total || 0, hasNext: Boolean(result.hasNext) }; resourcePackResults = result.results || []; $('resourcePackSearchStatus').textContent = `${resourcePackSearchState.total.toLocaleString('de-DE')} kompatible Treffer · Seite ${resourcePackSearchState.page + 1}`; renderResourcePacks(); }
async function downloadResourcePack(index, button) { const pack = resourcePackResults[index]; const version = $('resourcePackVersion').value || selectedVersion; if (!pack) return; button.disabled = true; button.textContent = 'Lädt …'; const result = await window.vortex.downloadResourcePack(version, { projectId: pack.projectId, versionId: pack.versionId }); if (result.ok) { button.textContent = 'Installiert'; addLog(`${result.fileName} wurde in Minecraft ${result.version} installiert.`, 'success'); } else { button.disabled = false; button.textContent = 'Erneut versuchen'; addLog(result.error || 'Resource Pack konnte nicht geladen werden.', 'error'); } }

function showPage(page) { document.querySelectorAll('.page').forEach(element => element.classList.toggle('active', element.id === page)); document.querySelectorAll('.nav-link').forEach(element => element.classList.toggle('active', element.dataset.page === page)); if (page === 'mods') { modScopeLabel(); refreshInstalled(); } if (page === 'overview') renderOverview(); if (page === 'updates') updateUpdateView(); }
async function refresh() { launcherState = await window.vortex.getState(); selectedVersion = launcherState.state?.selectedVersion || '1.21.11'; selectedHat = launcherState.state?.hat || 'vortex-cap'; selectedEmblem = launcherState.state?.emblem || 'vortex-crest'; setAccount(launcherState.account); renderVersions(); renderInstanceCards(); updatePlaySummary(); updateCosmetics(); updateUpdateView(launcherState.update); modScopeLabel(); await refreshInstalled(); await renderOverview(); }
async function login() { const button = $('loginBtn'); button.disabled = true; addLog('Microsoft-Anmeldung wird gestartet …'); const result = await window.vortex.login(); if (result.ok) { setAccount(result.account); addLog(`Angemeldet als ${result.account.username}`, 'success'); } else { addLog(result.error, 'error'); setAccount(null); } }
async function logout() { await window.vortex.logout(); setAccount(null); addLog('Konto abgemeldet.'); }
async function prepare(version = selectedVersion) { const button = $('prepareBtn'); if (button) button.disabled = true; setStatus(`Prüfe Instanz ${version} …`); addLog(`Vortex-Instanz ${version} wird bereitgestellt …`); const result = await window.vortex.prepareInstance(version); if (result.ok) { addLog(`Instanz ${version}: ${result.instance.coreModCount} Pflichtmods geprüft und bereitgestellt.`, 'success'); await refresh(); } else addLog(result.error, 'error'); if (button) button.disabled = false; }
async function launch() { $('playBtn').disabled = true; $('playLabel').textContent = 'Startet …'; const result = await window.vortex.launch(selectedVersion); if (!result.ok) { addLog(result.error, 'error'); $('playBtn').disabled = false; $('playLabel').textContent = 'Vortex starten'; } }
async function saveCosmetics(patch) { const result = await window.vortex.setCosmetics({ hat: selectedHat, emblem: selectedEmblem, ...patch }); if (!result.ok) { addLog(result.error || 'Cosmetic konnte nicht gespeichert werden.', 'error'); return; } selectedHat = result.hat; selectedEmblem = result.emblem; updateCosmetics(); addLog(`Cosmetics-Auswahl gespeichert: ${hatNames[selectedHat]} + ${emblemNames[selectedEmblem]}.`, 'success'); }
async function createCosmeticSkin() { const button = $('createCosmeticsBtn'); button.disabled = true; button.textContent = 'Skin wählen …'; const result = await window.vortex.importCosmeticSkin(launcherState.cosmeticsVersion, { hat: selectedHat, emblem: selectedEmblem }); if (result.ok) { addLog(`Cosmetic-Skin erstellt: ${result.profile.generatedSkin}`, 'success'); await refresh(); } else if (!result.canceled) addLog(result.error || 'Skin-Variante konnte nicht erstellt werden.', 'error'); button.disabled = false; button.textContent = 'Skin importieren & erstellen'; }

$('playBtn').onclick = launch; $('prepareBtn').onclick = () => prepare(); $('openModsBtn').onclick = () => window.vortex.openModsFolder(selectedVersion); $('openInstanceBtn').onclick = () => window.vortex.openInstanceFolder(selectedVersion); $('clearLog').onclick = () => { logEl.innerHTML = ''; }; $('cosmeticsInfoBtn').onclick = () => window.vortex.showCosmeticsInfo(); document.querySelectorAll('.nav-link').forEach(button => button.onclick = () => showPage(button.dataset.page)); document.querySelectorAll('[data-page-target]').forEach(button => button.onclick = () => showPage(button.dataset.pageTarget)); document.querySelectorAll('.hat-card').forEach(button => button.onclick = () => saveCosmetics({ hat: button.dataset.hat })); document.querySelectorAll('.emblem-card').forEach(button => button.onclick = () => saveCosmetics({ emblem: button.dataset.emblem })); $('createCosmeticsBtn').onclick = createCosmeticSkin; $('openSkinsBtn').onclick = () => window.vortex.openSkinsFolder(launcherState.cosmeticsVersion); $('modSearchBtn').onclick = searchTemplateMods; $('modQuery').onkeydown = event => { if (event.key === 'Enter') searchTemplateMods(); }; $('toggleInstalled').onclick = () => { installedCollapsed = !installedCollapsed; $('toggleInstalled').textContent = installedCollapsed ? 'Expand' : 'Collapse'; refreshInstalled(); }; $('searchResourcePacksBtn').onclick = () => searchResourcePacks(0); $('resourcePackSearchInput').onkeydown = event => { if (event.key === 'Enter') searchResourcePacks(0); }; $('packsPrevBtn').onclick = () => searchResourcePacks(Math.max(0, resourcePackSearchState.page - 1)); $('packsNextBtn').onclick = () => searchResourcePacks(resourcePackSearchState.page + 1); $('openProfileBtn').onclick = () => window.vortex.openCosmeticsProfile(launcherState.cosmeticsVersion); $('checkUpdateBtn').onclick = checkUpdate; $('downloadUpdateBtn').onclick = downloadUpdate; $('installUpdateBtn').onclick = installUpdate;
window.vortex.onStatus(({ type, message }) => { setStatus(message); addLog(message, type); if (type === 'success' && message.includes('gestartet')) { $('playBtn').disabled = false; $('playLabel').textContent = 'Vortex starten'; } }); window.vortex.onLog(message => addLog(message)); window.vortex.onProgress(data => { if (data?.type) setStatus(`Lade ${data.type} …`); }); window.vortex.onUpdateState(update => { if (launcherState) launcherState.update = update; updateUpdateView(update); });
addLog('Vortex Client Launcher 0.4.8 bereit.'); refresh();
